language: node_js
node_js:
  - "0.10"
  - "0.8"
notifications:
  email: false
before_install:
  - sudo apt-get install -qq vim
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8"  ] || npm install -g npm@1.4.28'
  - npm install -g npm
  - npm install
script: npm test
